version: "3.7"

services:
  web:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DB_USER=kubernetes
      - DB_PASSWORD=kubernetes1
    ports:
      - 4000:4000
    links:
      - mongodb

  mongodb:
    image: mongo:3.2.6
    environment:
      - DB_USER=kubernetes
      - DB_PASSWORD=kubernetes1
      - MONGO_DB=message
    volumes:
      - /private/var:/data/db
    ports:
      - "27017:27017"
