apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.2.6
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  - name: mongodb-credentials
                    key: user
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  - name: mongodb-credentials
                    key: password
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  - name: mongod-credentials
                    key: mongodbname
      restartPolicy: Always
      volume:

