# apiVersion: v1
# kind: Secret
# metadata:
#   name: database-credentials
# type: Opaque
# data:
#   user: TWF0dGhldw==
#   password: aWdvY2hlbWF0N0BA

# apiVersion: extensions/v1beta1
# kind: Deployment
# metadat:
#   name: node-deployment
#   labels: 
#     app: node
# spec:
#   replicas: 1
#   template:
#     metadata:
#       name: node
#       labels:
#         name: node
#     containers:
#       - name: node
#         image: gcr.io/kubernetesproject-232209
#         env:
#           - name: NODE_ENV
#             value: "development"
#           - name: PORT
#             value: "4000"
#     restartPolicy: Always

# apiVersion: v1
# kind: Service
# metadata:
#   name: node-service
#   labels:
#     service: node
# spec:
#   selector:
#     app: node
#   type: LoadBalancer
#   ports:
#     - port: 4000

apiVersion: v1
kind: PersistenceVolume
metadata: 
  name: persistence-v
  labels:
    name: persistence-v
spec:
  capacity:
    storage: 50GB
  storageClassName: standard
  accessMode:
    - readWriteOnce
  gcePersistenceDisk:
    
  
