apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: kubernetes-test
          image: gcr.io/kubernetesproject-232209/kubernetes-test:v1.0.0 
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "4000"

