apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-pv
spec:
  capacity:
    storage: 50Gi
  storageClassName: standard
  accessModes: 
    - readWriteOnce
  gcePersistentDisk: 
    pdName: pg-data-disk
    fsType: ext4
